### ISSUE TITLE
Log is not written if realtive filename is used

### ISSUE THREAD

**Issue by KacerCZ** [paypal/sdk-core-php#101]
### General information

* SDK/Library version:3.3.2
* Language, language version, and OS: PHP 7.1 on Ubuntu 16.04

### Issue description

PR https://github.com/paypal/sdk-core-php/pull/86 changed the way log is written.
This causes trouble when relative filename is used in `log.FileName` INI setting resulting in `Warning: error_log(../log/PayPal.log): failed to open stream: No such file or directory`.

According to PHP documentation (http://php.net/manual/en/function.register-shutdown-function.php): Working directory of the script can change inside the shutdown function under some web servers, e.g. Apache.

Possible solution would be to note output of `getcwd()` in `PayPal\Core\PPLoggingManager` and use it in case relative path is supplied in configuration file.

**Comment by pp-randy** [comment]
Closing in favor of the PR https://github.com/paypal/sdk-core-php/pull/102. 
Thank you again for submitting.
