### ISSUE TITLE
 Call to a member function handle() line 75

### ISSUE THREAD

**Issue by kalianto** [paypal/sdk-core-php#44]
I was wondering if this is my issue, or is it a real issue?
PPAPIService.php line 75

$handlerClass->handle($httpConfig, $request, $options);

This sometimes generates error: Call to a member function handle() on a non object.
I am able to bypass the error by instantiating the $handlerClass from line 74.

$handlerClass = new $handlerClass();

I assume this is handlers class in sdk-core-php/lib/handlers

Thanks

Kal

**Comment by jaypatel512** [comment]
Hey @kalianto ! The Handler Class needs to be an object, when passing it. The SDKs referencing the SDK Core are fixed to pass in the objects, and not just the strings.
