### ISSUE TITLE
v2.5.2 handler issue

### ISSUE THREAD

**Issue by bram123** [paypal/sdk-core-php#45]
https://github.com/paypal/sdk-core-php/blob/v2.5.2/lib/PayPal/Transport/PPRestCall.php#L40

Has the code on line 40
```php
if (!is_object($handler)) {
    $shandler = "\\".$handler;
    $handler = new $shandler($this->apiContext);
}
```

Passing the apiContext object to the handler.
The problem here is that when I create a new payment using the REST API, it will use the handler RestHandler

https://github.com/paypal/sdk-core-php/blob/v2.5.2/lib/PayPal/Rest/RestHandler.php#L26

This class has two parameters in the construct on line 26.
```php
public function __construct($sdkName='rest-sdk-php', $sdkVersion='')
```

And not the apiContext.. So later on in the code it will try and use the sdkName (string), but it receives the apiContext class.. Causing a php crash.

**Comment by jaypatel512** [comment]
Hey @bram123 ! Rest handlers are not used by any dependencies, and will be removed in next stable release.
