### ISSUE TITLE
PPIPNMessage->validate() doesn't handle code 0

### ISSUE THREAD

**Issue by nbolton** [paypal/sdk-core-php#60]
I'm using PPIPNMessage->validate() and seeing this error coming back from PayPal intermittently. I know its an issue with the PayPal servers (on the 2nd attempt it succeeds) but it would be nice to see a retry mechanism implemented (rather than me having to haphazardly code one myself).

Here's the stack trace...

```
PPConnectionException: exception 'PPConnectionException' with message
  'Got Http response code 0 when accessing https://ipnpb.paypal.com/cgi-bin/webscr.'
  in vendor/paypal/sdk-core-php/lib/PPHttpConnection.php:104
Stack trace:
#0 vendor/paypal/sdk-core-php/lib/ipn/PPIPNMessage.php(96):
  PPHttpConnection->execute('cmd=_notify-val...')
#1 foo.php(1): PPIPNMessage->validate()
```

**Comment by jaypatel512** [comment]
Moving it to an enhancement, as the retry logic recommended would be an enhancement to the sdk. Will make a pull request, and get the feature in soon.

**Comment by jaypatel512** [comment]
On further review, we do want developers to have control over retries, instead of baking it directly in the SDK. This helps developer decide, and design their retry mechanism based on their setup.
