### ISSUE TITLE
 Class 'PayPal\\Auth\\Openid\\PPOpenIdSession' not found

### ISSUE THREAD

**Issue by xaccrocheur** [paypal/sdk-core-php#63]
Hi everybody at PayPal ; I'm probably doing something wrong, here goes :

Including all classes work except for PPOpenIdSession :

```
require 'PAYPAL/vendor/autoload.php';

use PayPal\Api\Address;
use PayPal\Api\CreditCard;
use PayPal\Api\Amount;
use PayPal\Api\Payer;
use PayPal\Api\Payment;
use PayPal\Api\Transaction;
use PayPal\Api\FundingInstrument;
use PayPal\Auth\Openid\PPOpenIdUserinfo;
use PayPal\Auth\Openid\PPOpenIdTokeninfo;
use PayPal\Auth\Openid\PPOpenIdAddress;
use PayPal\Auth\Openid\PPOpenIdSession; // <= But this one fails (not at this "use" line, but at the PPOpenIdSession:: class instantiation, later)
```
For each of those, I do have a corresponding file :
```
# ls vendor/paypal/sdk-core-php/lib/PayPal/Auth/Openid/ 
PPOpenIdAddress.php
PPOpenIdSession.php
PPOpenIdUserinfo.php
PPOpenIdError.php    
PPOpenIdTokeninfo.php
```

My redirect page code fails at :
```
$apiContext = new \PayPal\Rest\ApiContext(
                                          new \PayPal\Auth\OAuthTokenCredential(
                                                                                $clientId,     // ClientID
                                                                                $clientSecret      // ClientSecret
                                                                                )
                                          );

$scope = array('openid', 'email');
$redirectUri = 'http://example.com/redirect.php';
$openidurl = PPOpenIdSession::getAuthorizationUrl($redirectUri, $scope , $clientId,  $apicontext); // Error here : PHP Fatal error:  Class 'PayPal\\Auth\\Openid\\PPOpenIdSession' not found
```

Here is my composer file:
```
# cat composer.json 
{
    "name": "paypal/rest-api-sdk-sample-php",
    "description": "Samples using PayPal's REST API SDK for PHP",
    "homepage": "https://github.com/paypal/rest-api-sdk-php",
    "config": {
        "require-all": true
    },
    "require": {
        "php": ">=5.3.0",
        "ext-curl": "*",
        "ext-json": "*",
                "paypal/rest-api-sdk-php" : "0.8.*"
    }
}
```

I'm I really using the latest SDK?
I'm I making the right API (Auth) Calls?

**Comment by jaypatel512** [comment]
Hey @xaccrocheur !

The latest version of PayPal-PHP-SDK is [v1.2.0](https://github.com/paypal/PayPal-PHP-SDK/releases). In the newer versions, we have removed dependency from sdk-core-php internally, and wont be required anymore. 

There may have been some [breaking changes](https://github.com/paypal/PayPal-PHP-SDK/wiki/Breaking-Changes---1.0.0) on 1.0.0 release, that may affect the namespaces, however, we have enough [documentation](https://github.com/paypal/PayPal-PHP-SDK/wiki) to get your started.

Your composer.json could be now just:
```json
{
 "name": "paypal/rest-api-sdk-sample-php",
    "description": "Samples using PayPal's REST API SDK for PHP",
    "homepage": "https://github.com/paypal/rest-api-sdk-php",
    "config": {
        "require-all": true
    },
    "require": {
          "paypal/rest-api-sdk-php" : "1.*"
    }
}
```

The PPOpenId* classes have been moved to PayPal\Api namespace. E.g. [OpenIdSession Class]http://paypal.github.io/PayPal-PHP-SDK/docs/class-PayPal.Api.OpenIdSession.html

Here are some [samples for Identity APIs](http://paypal.github.io/PayPal-PHP-SDK/sample/#identity), that could help you get started fairly quickly.

However, feel free to let me know if you run into any issues upgrading the system, and I should be able to help you with that.

**Comment by xaccrocheur** [comment]
Hi @jaypatel512, and thank your for your kind answer ; 

> Here are some samples for Identity APIs, that could help you get started fairly quickly.

They all mention a bootstrap.php file ; If it is (this one)[https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/bootstrap.php] then I'm afraid I'm still hitting "class not found" problems :

My composer.json has been updated, I ran 

```
$ php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing paypal/sdk-core-php (dev-master)
Writing lock file
Generating autoload files
```

This is my redirect test page*

```
require 'PAYPAL/bootstrap.php';

// require __DIR__ . '/../bootstrap.php';
use PayPal\Api\OpenIdTokeninfo;
use PayPal\Exception\PayPalConnectionException;
session_start();

$code = $_GET['code'];
try {
  $accessToken = OpenIdTokeninfo::createFromAuthorizationCode(array('code' => $code), null, null, $apiContext);
} catch (PayPalConnectionException $ex) {
  ResultPrinter::printError("Obtained Access Token", "Access Token", null, $_GET['code'], $ex); exit(1);
  }
ResultPrinter::printResult("Obtained Access Token", "Access Token", $accessToken->getAccessToken(), $_GET['code'], $accessToken);
```

(Yes, I removed the `if (isset($_GET['success']) && $_GET['success'] == 'true')` test because those vars are not in the query string sent back by Paypal:

`http://example.com/redirect.php?scope=https%3A%2F%2Furi.paypal.com%2Fservices%2Fpaypalattributes+address+openid+profile+email+https%3A%2F%2Furi.paypal.com%2Fservices%2Fexpresscheckout+phone&code=LFxxRrne-b9t37FuT87nKiqYuwKgxpsiWGloUO_8NwGhqdIwUAe7qW0dCjqRXj1G8kpYdZKPh1bzEO-ELbPlnwxXvPi9I_xxxxxx5OKlSDf115Ffy2yzRuLHYVaUkkYSOTHu-H1PYtma19h3NOw3kf6_ImILtSsOrRZrwX8ENzODB0N-`

And I still get a
`PHP Fatal error:  Class 'ResultPrinter' not found` error :(

If you want to help me (which is very kind of you) please run me though the full installation procedure, ensureing that I'm requiring and including the right files.

Thank you very much.

**Comment by jaypatel512** [comment]
The result printer class is for demo only. You could follow the instructions on wiki and you should be able to get the code running. You do not need to use bootstrap.php

**Comment by jaypatel512** [comment]
Please follow the instructions here: https://github.com/paypal/PayPal-PHP-SDK/wiki/Making-First-Call

As you can see, you can create first.php, second.php and third.php, without using bootstrap.php file. You could then replace the code for your specific need after that.

**Comment by xaccrocheur** [comment]
I'm just trying to properly implement "login with paypal". Everything else works ; I succeeded months ago (by following a tutorial non the net) but I cannot, for the life of me, get the payer's openid when he comes back, on the redirect page. There is a [demo website](https://lipp.ebaystratus.com/loginwithpaypal-live/), but with the source code is not available (?).

Can you please post the code of the redirection page? That would really help me. 

Thank you very much

**Comment by xaccrocheur** [comment]
This is where I am right now :
```
require_once('libs/mysql_connect.php');

require __DIR__  . '/../PAYPAL/vendor/autoload.php';

$code = $_GET['code'];

$clientId = 'myId';
$clientSecret = 'mySecret';

$apiContext = new \PayPal\Rest\ApiContext(new \PayPal\Auth\OAuthTokenCredential($clientId, $clientSecret));

use PayPal\Api\OpenIdTokeninfo;
use PayPal\Api\OpenIdUserinfo;
use PayPal\Exception\PayPalConnectionException;


try {
  $accessToken = OpenIdTokeninfo::createFromAuthorizationCode(array('code' => $code), null, null, $apiContext);
}
catch (PayPalConnectionException $ex) {
  error_log('###################### Nope'); exit(1);
}

error_log('###################### Yup: ' . $accessToken);

$user_id = new  PayPal\Api\OpenIdUserinfo();

$user = $user_id->getUserinfo(array('access_token' => $accessToken)); // Error here
```

Produces :

```
PHP Fatal error:  Uncaught exception 'PayPal\\Exception\\PayPalInvalidCredentialException' with message 'Credential not found for  default user. Please make sure your configuration/APIContext has credential information' in /home/website/PAYPAL/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalCredentialManager.php:154\nStack trace:\n#0 /home/website/PAYPAL/vendor/paypal/rest-api-sdk-php/lib/PayPal/Rest/ApiContext.php(56): PayPal\\Core\\PayPalCredentialManager->getCredentialObject()\n#1 /home/website/PAYPAL/vendor/paypal/rest-api-sdk-php/lib/PayPal/Handler/RestHandler.php(51): PayPal\\Rest\\ApiContext->getCredential()\n#2 /home/website/PAYPAL/vendor/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php(71): PayPal\\Handler\\RestHandler->handle(Object(PayPal\\Core\\PayPalHttpConfig), '', Array)\n#3 /home/website/PAYPAL/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php(103): PayPal in /home/website/PAYPAL/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalCredentialManager.php on line 154
```

**Comment by jaypatel512** [comment]
You need to pass apicontext as a second parameter to your getUserInfo() method. You should be fine after that

**Comment by xaccrocheur** [comment]
My token object looks like this :
```
{\n    "token_type": "Bearer",\n    "expires_in": "900",\n    "refresh_token": "PQrTIPsnt4hGZ-2Ua9OB9Buu2aRZfGtybuDmnHB4jXosS9J11KD566DMQ1e9pTjnavzwSO6ygE7IqL7QBWl4jcf1bIP0-KY2lrp1KQT6OAaMHS9V73Nr4C-X2Lo",\n    "id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJBVzNIa0JDZjVXeVg1TEs0MHFiU01hWDdMT2g5blNGR3A0MzN6cGNnTkVaV3pXaFVGbG95cVJ6clRnSmMiLCJhdXRoX3RpbWUiOjE0MjM5NjM2NDcsImlzcyI6Imh0dHBzOi8vd3d3LnBheXBhbC5jb20iLCJzZXNzaW9uSW5kZXgiOiI4YTE2ZjdlYTRjZDIxMTdmNmJjZGEzYTY2NGMwOWViNWY3ZTRlNzFjIiwiaWF0IjoxNDIzOTYzNjYyLCJleHAiOjI4ODAwLCJub25jZSI6Ijg2NjQxMjM0IiwidXNlcl9pZCI6Imh0dHBzOi8vd3d3LnBheXBhbC5jb20vd2ViYXBwcy9hdXRoL2lkZW50aXR5L3VzZXIvaGxyOUNaVy1JelNKbWZ1ZUpFdWFaSllIdnQtOEpLTFZPbmJwdEtRc1FCQSJ9.D41AUpTr_K2BxGgDQzqmgY1QX2gpf4L4pLc0NmMfZJg",\n    "access_token": "A015UvIb.Lyns6MBsE.Jj3id.HF4n1.xR8Vxo1HvfCjEWd8"\n}
```

How do I retrieve the access token from it ? I tried `->getAccessToken()` method but got an error.

**Comment by jaypatel512** [comment]
Hey, would it make sense if we could look into this over a hangout session or something, where we could look at the code better.

**Comment by xaccrocheur** [comment]
This is my code right now:

````
require __DIR__  . '/../PAYPAL/vendor/autoload.php';

$code = $_GET['code'];

$clientId = 'AW3HkBCf5WyX5LK40qbSMaX7LOh9nSFGp433zpcgNEZWzWhUFloyqRzrTgJc';
$clientSecret = 'EO9QYhCrtELJKcI7lasy2sTxgeURNIHch37LdJiOYQ1EXh9O_75rdvrGMo_c';

$apiContext = new \PayPal\Rest\ApiContext(new \PayPal\Auth\OAuthTokenCredential($clientId, $clientSecret));

use PayPal\Api\OpenIdTokeninfo;
use PayPal\Api\OpenIdUserinfo;
use PayPal\Exception\PayPalConnectionException;

try {
  $accessToken = OpenIdTokeninfo::createFromAuthorizationCode(array('code' => $code), null, null, $apiContext);
}
catch (PayPalConnectionException $ex) {
  error_log('###################### Nope'); exit(1);
}

error_log('###################### Yup: ' . $accessToken);

$user = OpenIdUserinfo::getUserinfo(array('access_token' => $accessToken, $apiContext));

```

xaccrocheur@gmail.com

**Comment by xaccrocheur** [comment]
Please, tell me how I extract the access token from the object I got with `OpenIdTokeninfo::createFromAuthorizationCode(array('code' => $code), null, null, $apiContext)` and what are those two null params?

**Comment by xaccrocheur** [comment]
This is a nightmare.

**Comment by xaccrocheur** [comment]
Jay?

**Comment by xaccrocheur** [comment]
Jay, why don't you just tell me where the documentation for the `OpenIdTokeninfo` object is?

**Comment by xaccrocheur** [comment]
Hello?

**Comment by xaccrocheur** [comment]
Jay, what I want, is to retrieve the payer_id of my user when he logs in. This payer_id:

`[payer_id] => V8U3N383UT2BW`

That I **do** get when I list my transactions. Why don't you please tell me where the documentation is about how to get it ? Please.

**Comment by jaypatel512** [comment]
Hey @xaccrocheur ! Apologies for replying a bit late. Btw, you wont get the payer_id as a return for getUserInfo. This is how the call looks like:

![screen shot 2015-02-14 at 9 47 08 pm](https://cloud.githubusercontent.com/assets/1309895/6202001/16516c62-b493-11e4-8a53-b9dd9fa0013f.png)

As you can see, you do get email of the user. Also, when you do a normal checkout with Paypal, and execute the payment, you get the payer object inside the response. This is what you could use to co-relate between the user who is logged in, and transactions of each user. 

PayPal  uses email as an identifier for any user inside paypal. I hope I helped you answer this. However, I would strongly recommend to run samples in your local machine, that comes along with the SDK, and check out the request-response there. This helps you get a better idea on what you get back.

**Comment by xaccrocheur** [comment]
> Apologies for replying a bit late.
It's OK, thanks for your help Jay
> As you can see, you do get email of the user.
But what if the user changes email address? 
> Also, when you do a normal checkout with Paypal, and execute the payment, you get the payer object inside the response.
I know ! But I wanted something stronger than the email... OK so you are positive, the only object that is common between the transaction's payer object, and the payer itself, is the email?

Phil
