### ISSUE TITLE
PPIPNMessage::getTransactionType looking for the wrong value

### ISSUE THREAD

**Issue by jaypatel512** [paypal/sdk-core-php#64]
Moved from https://github.com/paypal/PayPal-PHP-SDK/issues/246

The PPIPNMessage::getTransactionType method returns null whenever I call getTransactionType() on an IPN notification.

After debugging I found the cause
```php
/**
	 * Returns the transaction type for which
	 * this IPN was generated
	 *
	 * @return string
	 */
	public function getTransactionType() {
		return $this->ipnData['transaction_type'];
	}
```

Should be:
```php
/**
	 * Returns the transaction type for which
	 * this IPN was generated
	 *
	 * @return string
	 */
	public function getTransactionType() {
		return $this->ipnData['txn_type'];
	}
```

Here is the raw output from an IPN notification sent by PayPal
```
POST /endpoint/notify/paypal/?XDEBUG_SESSION_START=nomnom HTTP/1.1

Host: 1d03791b.ngrok.com

User-Agent: Go 1.1 package http

Content-Length: 974

Accept: */*

Connection: close

Content-Type: application/x-www-form-urlencoded

X-Forwarded-Proto: http

X-Real-Ip: 209.139.233.227

Accept-Encoding: gzip



mc_gross=127.46&invoice=AABB-C1702151847-18XAK&protection_eligibility=Eligible&address_status=confirmed&payer_id=BDTNPC6SPDQ54&tax=0.00&address_street=1+Maire-Victorin&payment_date=10%3A45%3A57+Feb+17%2C+2015+PST&payment_status=Completed&charset=windows-1252&address_zip=M5A+1E1&first_name=Canada&mc_fee=4.00&address_country_code=CA&address_name=Canada+Visa&notify_version=3.8&custom=&payer_status=verified&address_country=Canada&address_city=Toronto&quantity=1&verify_sign=Aok-wnXsG3.bYhIn3KepjqfFI.w1At105Cy-bpu4obXltHrVDXewTH38&payer_email=qa%2Bcavisa%40revenuewire.com&memo=from+safecart.com&txn_id=9RA44460C2109111D&payment_type=instant&last_name=Visa&address_state=Ontario&receiver_email=rwtest%40revenuewire.com&payment_fee=&receiver_id=YQSBCL38QM46U&txn_type=express_checkout&item_name=&mc_currency=CAD&item_number=&residence_country=CA&test_ipn=1&handling_amount=0.00&transaction_subject=&payment_gross=&shipping=0.00&ipn_track_id=1b341a7587447&cmd=_notify-validate
```

If we can get a fix patched in ASAP as this has a pretty big impact on IPN processing with the PHP SDK.

This is in the namespace-php-5.3 branch, have not verified it on other branches.

**Comment by MavenSean** [comment]
From a related issue:

>IPNs for WP Pro / Express Checkout and WPS (Merchant and Button Manager APIs) contain the >txn_type field while IPNs for the Adaptive Payments / Adaptive Accounts APIs contain the >transaction_type field. You will notice that the IPN simulator supports only Merchant APIs at this point >hence it uses txn_type.

That being the case, we are on WP Pro/Express Checkout.  The Merchant SDK should be able to handle either or, perhaps a simple:

```php
	public function getTransactionType() {
                if (empty($this->ipnData['transaction_type']) {
		        return $this->ipnData['txn_type'];
                }

		return $this->ipnData['transaction_type'];
	}
```

**Comment by jaypatel512** [comment]
Agreed. I think having both compatible change would make sense. I will update this change, and make a commit soon.

**Comment by MavenSean** [comment]
Thanks Jay, much obliged man.  Do you know if there is a plan to deploy the REST API to Canada anytime soon?

**Comment by jaypatel512** [comment]
Personally, I am not aware of that, as that is outside the scope of my work. Considering that we are developing REST api to be in parity with Classic APIs, with a small group supporting just US for now, there are definitely plans to expand it as it gets more and more stable. However, I will definitely find it out, and update that to you as soon as possible.

**Comment by jaypatel512** [comment]
Hey @MavenSean ! 

I have updated the code accordingly. Can you please verify if that works, and I would be more than happy to make a release soon. 

In the mean time you could use `dev-namespace-5.3` as your version in composer, and you should be able to use this change.

**Comment by jaypatel512** [comment]
Updated in `master` branch too (Non-Namespaced PHP SDK).

**Comment by MavenSean** [comment]
Thanks Jay, that looks good

**Comment by MavenSean** [comment]
Jay can we get an updated tag on this?

**Comment by jaypatel512** [comment]
Yes. I am working on this. I was just waiting for you to confirm it it worked. I will make a tag in few minutes.

**Comment by MavenSean** [comment]
Thanks Jay, much obliged

**Comment by jaypatel512** [comment]
Released : https://github.com/paypal/sdk-core-php/releases/tag/v2.5.9
