### ISSUE TITLE
CHANGELOG.md is not being updated

### ISSUE THREAD

**Issue by shakaran** [paypal/sdk-core-php#67]
As you can see here the latest update is from 2013.

https://github.com/paypal/sdk-core-php/blob/master/CHANGELOG.md

It is hard to follow the remarkable changes if you don't see the git history or brief description in https://github.com/paypal/sdk-core-php/releases

**Comment by jaypatel512** [comment]
We are now making sure to update the changelog. Thanks for pointing that out.
