### ISSUE TITLE
Namespace Error

### ISSUE THREAD

**Issue by ChiarilloMassimo** [paypal/sdk-core-php#68]
Is impossibile to use `paypal/rest-api-sdk-php` with `paypal/adaptiveaccounts-sdk-php` or `paypal/sdk-core-php`.

There are two classes with the same namespace `PayPal\Rest\ApiContext`

- vendor/paypal/sdk-core-php/lib/PayPal/Rest/ApiContext.php
- vendor/paypal/rest-api-sdk-php/lib/PayPal/Rest/ApiContext.php

PHP return FATAL ERROR: `Call to undefined method PayPal\Rest\ApiContext::getRequestHeaders()`

**Comment by jaypatel512** [comment]
Which version of adaptiveaccounts-sdk-php are you using ?

**Comment by ChiarilloMassimo** [comment]
I use `"paypal/adaptiveaccounts-sdk-php": "^3.8" with `"paypal/rest-api-sdk-php": "^1.5"`

**Comment by jaypatel512** [comment]
i realized the sdk-core-php dependency in adaptiveaccounts-sdk-php has not being updated to latest [3.0](https://github.com/paypal/adaptiveaccounts-sdk-php/blob/namespace-php5.3/composer.json#L16).

**Comment by jaypatel512** [comment]
I just updated the `namespace-php5.3` branch to use latest [sdk-core-php](https://github.com/paypal/sdk-core-php/releases/tag/v3.0.0) that has the fix. 

Would you mind just trying out replacing your composer json to use `dev-namespace-php5.3` as a version as:

```
"paypal/adaptiveaccounts-sdk-php": "dev-namespace-php5.3"
```

Let me know if that resolves the issue for you now. If you are, I will make a release today with the fix on all classic SDKs.

**Comment by ChiarilloMassimo** [comment]
Yeaa it's working thanks ;)

**Comment by odimodugno** [comment]
:clap:

**Comment by jaypatel512** [comment]
Great :) I will make a release today, with the updates, and you should be able to use the normal versions just fine.

**Comment by ChiarilloMassimo** [comment]
Hi Jay, the latest version of `paypal/adaptiveaccounts-sdk-php` require again `paypal/sdk-core-php: 2.5.*`

**Comment by jaypatel512** [comment]
Release made for adapativeaccounts-sdk-php with the fix : https://packagist.org/packages/paypal/adaptiveaccounts-sdk-php

**Comment by adfinlay** [comment]
It would seem that https://packagist.org/packages/paypal/merchant-sdk-php is still on paypal/sdk-core-php: 2.5.* as well. Can this be updated?
