### ISSUE TITLE
Fatal error:  Class 'PayPal\Core\PPTokenAuthorization' not found

### ISSUE THREAD

**Issue by fonshua** [paypal/sdk-core-php#69]
When using sdk-core-php v3.0.0, I get:

Class 'PayPal\Core\PPTokenAuthorization' not found in /opt/app/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPCredentialManager.php on line 118

It seems that PPTokenAuthorization class is located under Auth instead of Core directory. After I added use PayPal\Auth\PPTokenAuthorization; it seems to work again.

And in line 116:  
```
else if($userName && (isset($credArr[$key . 'accessToken']) && isset($credArr[$key . 'tokenSecret']))) {
```
The is a missing dot (.) to separate the key and the property. So the script doesn't recognize acct1.accessToken but acct1accessToken

**Comment by ppmtscory** [comment]
@fonshua if you know of the specific issues within the SDK with the filepath and syntax, please submit a PR against the repo and we'll have somebody take a look.  With our focus on the REST SDKs currently, a pull request with the correct fix will help us to prioritize.
