### ISSUE TITLE
Fatal error: Uncaught Error: Class 'string' not found in vendor/paypal/sdk-core-php/lib/PayPal/Core/PPMessage.php:104 

### ISSUE THREAD

**Issue by Jossnaz** [paypal/sdk-core-php#92]
i know those exist:
https://github.com/paypal/sdk-core-php/issues/34
https://github.com/paypal/sdk-core-php/issues/7
https://github.com/paypal/sdk-core-php/pull/32

but I still have the issue even with the following versions:

> paypal/adaptivepayments-sdk-php     v3.9.2 PayPal adaptivepayments SDK for PHP
> paypal/sdk-core-php                 3.3.0  PayPal Core SDK for PHP
> PHP Version 7.0.12-1+deb.sury.org~xenial+1

Note: I did not! have this issue on my local dev machine and on two servers of digital ocean. So this worked fine on 3 servers. It does not work though, on the new host we are moving to. So i guess it must be some php.ini or environment problem.

the code causing the problem

```

            } else { // one object
                $this->{$property} = new $type();
```

full stack trace i receive:

`Fatal error: Uncaught Error: Class 'string' not found in /www/MyApp_411/public/japi_lib/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPMessage.php:104 Stack trace: #0 /www/MyApp_411/public/japi_lib/vendor/paypal/adaptivepayments-sdk-php/lib/PayPal/Service/AdaptivePaymentsService.php(215): PayPal\Core\PPMessage->init(Array) #1 /www/MyApp_411/public/japi_lib/src/MyApp/Service/JcrPayPalService.php(119): PayPal\Service\AdaptivePaymentsService->Pay(Object(PayPal\Types\AP\PayRequest)) #2 /www/MyApp_411/public/japi_lib/src/MyApp/Service/JcrPayPalService.php(78): MyApp\Service\JcrPayPalService::doPreparePayment(0.05, 1, 'https://MyApp....', 'https://MyApp....', Object(MyAppProject)) #3 /www/MyApp_411/public/japi_lib/src/MyApp/Service/JcrPayPalService.php(27): MyApp\Service\JcrPayPalService::preparePayment(1, false, 5, 'https://MyApp....', 'https://MyApp....', Object(MyAppProject)) #4 /www/MyApp_411/public/japi_lib/src/routes/routes_funding.php(83): MyApp\Service\JcrPayPalService::initPaypalProcess('335495', 'jcr_5 in /www/MyApp_411/public/japi_lib/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPMessage.php on line 104`

**Comment by jaypatel512** [comment]
Hey @Jossnaz !

Can you check if by replacing [Line 75 of PPMessage.php](https://github.com/paypal/sdk-core-php/blob/master/lib/PayPal/Core/PPMessage.php#L75) to below fixes the issue ? If so, I can go ahead and push the change out soon. 

```php
if (!$this->isBuiltInType($type) && !class_exists($type = PPUtils::propertyType($this, $property))) {
                 trigger_error("Class $type not found.", E_USER_NOTICE);
                 continue; // just ignore
             }
```

**Comment by Jossnaz** [comment]
@jaypatel512  it does fix it. And it was difficult to see why it is different at all. Makes it an anti pattern to me using variable definition in function calls and expressions... just makes it unnecessary hard to read.

**Comment by jaypatel512** [comment]
Sounds good ! I will go ahead and make the changes. The issue is with the `if` condition, where we need to check first if the type is built-in or not, and if not, check if the class exists. 

This code is quite old, and has not been given much love as we have moved to newer REST APIs for most use cases. However, we would love to have some help from the external dev help us make this SDK even better.

**Comment by Jossnaz** [comment]
@jaypatel512 you made a mistake in your patch. Your patch is the same as the old code, only with the variable definition outside. It does not fix the error. Another reason why to not do variable definitions in expressions. Imho the most readable thing is to use this:

```


      if (!$this->isBuiltInType($type)) {
        $type = PPUtils::propertyType($this, $property);
        if (!class_exists($type)) {
          trigger_error("Class $type not found.", E_USER_NOTICE);
          continue; // just ignore
        }
      }
```
yes, it is more code, yes, there are 2 ifs. But at least you can see in a glance that `$type` gets changed for the remainder of the code, that is, if `class_exists` is true, $type won't be the same any more for the rest of the code. If that is a bug or not I don't know, but i don't feel like playing around with it really.

**Comment by jaypatel512** [comment]
You are absolutely correct. My bad on that. Let me get that taken care of.

**Comment by jaypatel512** [comment]
Hey @Jossnaz !

I have made a PR with the changes. The changes you recommended are not going to work as such. I fixed the $type assignment. It was indeed confusing. I tried to make it a bit more simpler than before. 

Can you please do me a favor and test that out for your case please.

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.
