### ISSUE TITLE
Confused with what Credentials set to use

### ISSUE THREAD

**Issue by dmahesh22** [paypal/sdk-core-php#95]
Hi,

 As mentioned in [this](https://github.com/paypal/sdk-core-php/wiki/Configuring-the-SDK) link, what I understood is we have to set API credentials for `acct1`, `acct2`, `acct3`. For me confusion is, `acct1` and `acct2` sets are replaceable ? i,e. I have to configure either of two sets or both are mandatory ?. In `Sandbox` mode without setting `acct2` values I'm authenticated. What about in `live` mode and can I use same `cacert.pem` file in for `live` mode too ?

**Comment by xiaoleih41** [comment]
Thank you for your query. PayPal classic API can be configured by two types API credentials. One is API signature and the other is API certificate. PayPal SDK allows you to configure multiple accounts but if you only have one account to configure, you just have to choose one method only for your account. You don't have to configure a second account.

 In live mode, you will have to generate new live API signature or API certificate. Personally, I believe signature is easier to integrate.  To learn more about how to switch from sandbox to live API credential, please check into this article. https://developer.paypal.com/docs/classic/lifecycle/goingLive/?mark=API%20credentials%20configuration
